#!/bin/bash

#Faire le ping d'un serveur avec le code retour $?
#Toujours déclarer l'addr du serveur en 1ère position
#HOTE=$1
#NOMBRE_PAQUETS=$2
#ping -c $NOMBRE_PAQUETS $HOTE

#if [ $? -ne 0 ]; then
#	echo "L'hote $HOTE n'est pas joignable"
#else
#	echo "L'hote $hote est joignable"
#fi

#Arrêter le script avec "exit 0 ou 1" dans la condition si (if) .
HOTE="$1"
NOMBRE_DE_PAQUETS="$2"
ping -c $NOMBRE_DE_PAQUETS $HOTE
if [ $? != 0 ]; then
	echo "L'hote $HOTE n'est pas joignable"
	exit 1
else
	echo "L'hote $HOTE est joignable"
	exit 0
fi

