#!/bin/bash

#créer un compteur qui affiche les nombres de 20 à 0 
#et qui se répète tant qu'on n'a pas saisi de nbre.
#while [ -z $COMPTEUR ]; do
#	read -p "Saisir un chiffre pour le compteur : " COMPTEUR
#	while [ $COMPTEUR -gt 0 ]; do
#		echo "Le compteur est à $COMPTEUR"
#		COMPTEUR=$(( $COMPTEUR -1 ))
#	done
#done

#Créer un compteur qui nous demande de saisir un nbre de 20 et
#qui ne va pas se répété
#read -p "Saisir le chiffre du compteur : " COMPTEUR
#while [ $COMPTEUR -gt 0 ]; do
#	echo "Le compteur est à $COMPTEUR"
#	COMPTEUR=$(( $COMPTEUR -1 ))
#done

#Utilisation de la formule mathématique "expr"
#read -p "Saisir le chiffre du compteur : " COMPTEUR
#while [ $COMPTEUR -gt 0 ]; do
#	 echo "Le compteur est à $COMPTEUR"
#        COMPTEUR=`expr $COMPTEUR - 1`
#done

#Utilistation de la boucle for
read -p "Saisir un chiffre : " CHIFFRE
for (( cpt=1; cpt=$CHIFFRE; cpt=$CHIFFRE -1 )); do
	if [ $CHIFFRE -gt 0 ]; then
	echo "Le résultat de cpt est $cpt"
	CHIFFRE=`expr $CHIFFRE - 1`
	fi
done

