#!/bin/bash

#Script capable de modifier les droits sur le fichier rentré 
#par l'utilisateur, du propriétaire, du groupe, et des autres.

verif_existence_fichier() {
	ls $1 2> /dev/null
	if [ $? -eq 0 ]; then
		return 0
	else
		return 1
	fi
}

#Modification des droits d'accès de ts les users
echo Droits d\'accès pour les users : r=lecture, w=écrire et x=exécuter
echo Trois types de user : propriétaire, groupe et autre
echo " "
read -p "Quel est le fichier dont les droits d'accès sont à modifier ? " nom_fichier
verif_existence_fichier $nom_fichier
if [ $? = 0 ]; then
       	echo Modification des droits d\'accès du proprio	
	read -p "Quels sont les nouveaux droits d'accès du proprio ? " user_access
	chmod u+$user_access $nom_fichier
	echo " "
	echo Modification des droits d\'accès du groupe 
        read -p "Quels sont les nouveaux droits d'accès du groupe ? " group_access
	chmod g+$group_access $nom_fichier
	echo " "
	echo Modification des droits d\'accès des autres 
	read -p "Quels sont les nouveaux droits d\'accès des autres ? " other_access
	chmod o+$other_access $nom_fichier
else
	echo Le fichier $nom_fichier n\'existe pas
	exit 2
fi

