#!/bin/bash

function check_if_user_exist() {

#Recupération de la liste des utilisateur
list_users=`cut -d: -f1 /etc/passwd`

for users in $list_users; do
        if [ $1 = $users ]; then
                #echo "L'utilisateur $1 semble déjà exister"
                return 1
        fi
done

}

clear
read -p "Merci d'entrer le nom de l'utilisateur à vérifier : " name
#Verifie si l'utilisateur n'existe pas déjà
check_if_user_exist $name
if [ $? -eq 1 ]; then
        echo "L'utilisateur $name semble déjà exister"
        exit 1
else
        echo "L'utilisateur $name ne semble pas exister"
fi
